### PR TITLE
Create environemnt.yml

### PR DESCRIPTION
**Pull request by mainguyenanhvu**
I add a yml file to create conda env faster.

### CODE REVIEW

**Comment by patrickbryantlab** [comment]
Hi, 
We appreciate the yml file, but there seem to be many packages that are not used in umol installed(?). We would like to keep the installation as flexible as possible so we simply list the packages for local installation.

**Comment by mainguyenanhvu** [comment]
I created a completely new conda environment and installed following your instruction. After that, I exported to yml file. Therefore,   I think there is no redundant package.

**Comment by patrickbryantlab** [comment]
I think that when you export the env, you include packages specific to your local system. This is why the yml has to be defined only based on the packages that are to be installed.

**Comment by mainguyenanhvu** [comment]
Let me check that. However, I would like to ask you how to check whether these packages come from activated conda environment because I only activate base and umol environment?

**Comment by patrickbryant1** [comment]
Hi,
We provide the possibility to install the packages in any type of virtual environment. I can't help you with your pull request - it is up to you to provide all information if you want to suggest improvements. As of now, we will not include a yml.

**Pull request closed without merging**
